name: Latest blog posts
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -uses: sergdrozdov/blog-post-workflow@main
       with:
         comment_tag_name: "BLOG-POST-LIST"
         feed_list: "http://sd.blackball.lv/rss"
         max_post_count: 10
         accept_header: application/rss+xml